# Workaround for https://github.com/conda-forge/opencv-feedstock/issues/493
MACOSX_SDK_VERSION:        # [osx]
  - "15.5"                 # [osx]
channel_sources:
  - conda-forge/label/capstone_dev,conda-forge
